---
title: "Plots"
author: "Nathalie Fadel"
date: "11/2/2018"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(p8105.datasets)
library(viridis)
library(plotly)
library(flexdashboard)

```

```{r}
set.seed(1)

ny_noaa_data <- p8105.datasets::ny_noaa %>%
janitor::clean_names() %>%
  separate(date, c("year", "month", "day"), sep = "-") %>%
  mutate(prcp = prcp / 10, 
         tmax = as.numeric(tmax) / 10,
         tmin = as.numeric(tmin) / 10,
         year = as.integer(year), 
         month = month.name[as.integer(month)])  
```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}
ny_noaa_data %>%
  filter(month %in% c("January")) %>%
  group_by(year, month) %>%
  summarize(avg_high = mean(tmax, na.rm = TRUE)) %>%
  plot_ly(x = ~year, y = ~avg_high, type = "scatter", 
          mode = "markers", alpha = 0.5)

```

Column {data-width=500}
-----------------------------------------------------------------------

### Chart B

```{r}
ny_noaa_data %>%
  filter(month %in% c("July")) %>%
  group_by(year, month) %>%
  summarize(avg_high = mean(tmax, na.rm = TRUE)) %>%
  plot_ly(x = ~year, y = ~avg_high, type = "scatter", 
          mode = "markers", alpha = 0.5)
```

### Chart C

```{r}
temps = ny_noaa_data %>%
  filter(!is.na(tmin), !is.na(tmax)) %>%
  ggplot(aes(x = tmin, y = tmax)) +
  geom_bin2d() +
  viridis::scale_fill_viridis(option = "inferno") +
  theme(legend.position = "bottom", legend.key.size = unit(1.25, "cm"))

ggplotly(temps)

rmarkdown::render("My_website.Rmd", output_format = "My_website")
```











